services:
    mongo:
        image: mongo
        logging:
            driver: none
    app:
        build: .
        environment:
            WAIT_HOSTS: mongo:27017
        ports:
            - '8080:8000'
